spring:
  application:
    name: discovery-server

eureka:
  server:
    enable-self-preservation: false  # Optional: Disables self-preservation mode for testing/development
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761
  servlet:
    context-path: /eureka
